# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notes' do
  pod 'CorePlot', 2.2

  # Pods for Notes

  target 'NotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
